import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import dayjs from "dayjs";

import {
    AttendanceReport,
    AttendanceSummary,
} from "@/types/attendance";

interface ExportAttendancePdfProps {
    rows: AttendanceReport[];
    summary: AttendanceSummary[];
    fromDate?: string;
    toDate?: string;
    postingPlace?: string;
    section?: string;
    generatedBy?: string;
}

export function exportAttendancePdf({
    rows,
    summary,
    fromDate,
    toDate,
    postingPlace = "All Posting Places",
    section = "All Sections",
    generatedBy = "System",
}: ExportAttendancePdfProps) {
    const doc = new jsPDF({
        orientation: "landscape",
        unit: "mm",
        format: "a4",
    });

    console.log("postingPlace", postingPlace);
    console.log("section", section);
    console.log("generatedBy", generatedBy);

    const pageWidth = doc.internal.pageSize.getWidth();

    // ========================================
    // Professional Header
    // ========================================

    doc.setFillColor(245, 247, 250);
    doc.rect(0, 0, pageWidth, 32, "F");

    doc.setDrawColor(30, 64, 175);
    doc.setLineWidth(1.2);
    doc.line(14, 30, pageWidth - 14, 30);

    doc.setFont("helvetica", "bold");
    doc.setFontSize(18);
    doc.setTextColor(15, 76, 129);

    doc.text(
        "SINDH TECHNICAL EDUCATION & VOCATIONAL TRAINING AUTHORITY",
        pageWidth / 2,
        11,
        {
            align: "center",
        }
    );

    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.setTextColor(90);

    doc.text(
        "Government of Sindh",
        pageWidth / 2,
        17,
        {
            align: "center",
        }
    );

    doc.setFont("helvetica", "bold");
    doc.setFontSize(14);
    doc.setTextColor(0);

    doc.text(
        "ATTENDANCE REPORT",
        pageWidth / 2,
        25,
        {
            align: "center",
        }
    );

    // ========================================
    // Report Information
    // ========================================

    let y = 40;

    doc.setFillColor(248, 250, 252);
    doc.roundedRect(14, y - 4, pageWidth - 28, 28, 2, 2, "F");

    doc.setDrawColor(15, 76, 129);
    doc.setLineWidth(0.2);
    doc.roundedRect(14, y - 4, pageWidth - 28, 28, 2, 2);

    doc.setFont("helvetica", "bold");
    doc.setFontSize(10);
    doc.setTextColor(60);

    // Left Column
    doc.text("Report Period", 18, y + 2);
    doc.text("Posting Place", 18, y + 10);
    doc.text("Section", 18, y + 18);

    // Right Column
    doc.text("Generated By", 170, y + 2);
    doc.text("Generated On", 170, y + 10);

    doc.setFont("helvetica", "normal");
    doc.setTextColor(30);

    // Report Period
    const reportPeriod =
        fromDate && toDate
            ? `${dayjs(fromDate).format("DD MMM YYYY")} - ${dayjs(toDate).format("DD MMM YYYY")}`
            : fromDate
                ? dayjs(fromDate).format("DD MMM YYYY")
                : "-";

    doc.text(reportPeriod, 55, y + 2);

    doc.text(postingPlace, 55, y + 10);

    doc.text(section, 55, y + 18);

    doc.text(generatedBy, 205, y + 2);

    doc.text(
        dayjs().format("DD MMM YYYY hh:mm A"),
        205,
        y + 10
    );

    y += 34;

    // ========================================
    // Report Statistics
    // ========================================

    const reportingDays = summary.length;

    const totalEmployees =
        summary.length > 0
            ? Math.max(...summary.map(item => item.totalStaff))
            : 0;


    const totalRecords = rows.length;

    const cardY = y;

    const cardWidth = 55;
    const cardHeight = 18;
    const gap = 8;

    const statistics = [
        {
            title: "Reporting Days",
            value: reportingDays,
        },
        {
            title: "Employees",
            value: totalEmployees,
        },
        {
            title: "Attendance Records",
            value: totalRecords,
        },
    ];

    statistics.forEach((item, index) => {

        const x =
            14 +
            index * (cardWidth + gap);

        doc.setFillColor(248, 250, 252);

        doc.roundedRect(
            x,
            cardY,
            cardWidth,
            cardHeight,
            2,
            2,
            "F"
        );

        doc.setDrawColor(15, 76, 129);

        doc.roundedRect(
            x,
            cardY,
            cardWidth,
            cardHeight,
            2,
            2
        );

        doc.setFontSize(8);

        doc.setFont("helvetica", "normal");

        doc.setTextColor(0);

        doc.text(
            item.title,
            x + 4,
            cardY + 6
        );

        doc.setFontSize(16);

        doc.setFont("helvetica", "bold");

        doc.setTextColor(30, 64, 175);

        doc.text(
            String(item.value),
            x + 4,
            cardY + 14
        );
    });

    y += 34;

    // =============================
    // Summary Cards
    // =============================

    doc.setFont("helvetica", "bold");

    doc.setFontSize(13);

    doc.setTextColor(30, 64, 175);

    doc.text(
        "ATTENDANCE SUMMARY",
        14,
        y
    );

    doc.setDrawColor(30, 64, 175);

    doc.setLineWidth(0.5);

    doc.line(
        14,
        y + 2,
        75,
        y + 2
    );

    doc.setTextColor(0);

    y += 6;

    const summaryTotals = summary.reduce(
        (acc, item) => {
            acc.totalStaff = Math.max(acc.totalStaff, item.totalStaff);
            acc.present += item.present;
            acc.absent += item.absent;
            acc.late += item.late;
            acc.earlyCheckout += item.earlyCheckout;
            acc.notMarked += item.notMarked;

            return acc;
        },
        {
            totalStaff: 0,
            present: 0,
            absent: 0,
            late: 0,
            earlyCheckout: 0,
            notMarked: 0,
        }
    );

    const attendancePercentage =
        summaryTotals.totalStaff > 0 && summary.length > 0
            ? (
                (summaryTotals.present /
                    (summaryTotals.totalStaff * summary.length)) *
                100
            ).toFixed(2)
            : "0.00";

    autoTable(doc, {
        startY: y,
        margin: {
            left: 14,
            right: 14,
        },

        head: [[
            "Date",
            "Total Staff",
            "Present",
            "Absent",
            "Late",
            "Early Out",
            "Not Marked",
            "Attendance %"
        ]],

        body: summary.map(item => [
            item.date,
            item.totalStaff,
            item.present,
            item.absent,
            item.late,
            item.earlyCheckout,
            item.notMarked,
            `${item.attendancePercentage}%`,
        ]),

        didParseCell(data) {

            if (
                data.section === "body" &&
                data.column.index === 7
            ) {

                const value = Number(
                    String(data.cell.raw).replace("%", "")
                );

                if (value >= 95) {

                    data.cell.styles.textColor = [22, 163, 74];

                    data.cell.styles.fontStyle = "bold";

                } else if (value >= 85) {

                    data.cell.styles.textColor = [245, 158, 11];

                    data.cell.styles.fontStyle = "bold";

                } else {

                    data.cell.styles.textColor = [220, 38, 38];

                    data.cell.styles.fontStyle = "bold";

                }
            }

            if (data.section === "foot") {

                data.cell.styles.fontStyle = "bold";
            }
        },

        foot: [[
            "TOTAL",
            summaryTotals.totalStaff,
            summaryTotals.present,
            summaryTotals.absent,
            summaryTotals.late,
            summaryTotals.earlyCheckout,
            summaryTotals.notMarked,
            `${attendancePercentage}%`,
        ]],

        footStyles: {
            fillColor: [15, 76, 129],
            textColor: 255,
            fontStyle: "bold",
            halign: "center",
        },

        theme: "grid",

        styles: {
            fontSize: 8,
            cellPadding: 3,
            valign: "middle",
        },

        columnStyles: {
            0: {
                halign: "center",
                cellWidth: 28,
            },
            1: {
                halign: "center",
                cellWidth: 24,
            },
            2: {
                halign: "center",
                cellWidth: 24,
            },
            3: {
                halign: "center",
                cellWidth: 24,
            },
            4: {
                halign: "center",
                cellWidth: 22,
            },
            5: {
                halign: "center",
                cellWidth: 25,
            },
            6: {
                halign: "center",
                cellWidth: 28,
            },
            7: {
                halign: "center",
                cellWidth: 28,
            },
        },

        headStyles: {
            fillColor: [15, 76, 129],
            textColor: 255,
            fontStyle: "bold",
            halign: "center",
        },

        bodyStyles: {
            textColor: 50,
        },

        alternateRowStyles: {
            fillColor: [248, 250, 252],
        },
    });

    // ========================================
    // Start Employee Attendance Details on New Page
    // ========================================

    doc.addPage();

    y = 20;

    // Title
    doc.setFont("helvetica", "bold");
    doc.setFontSize(13);
    doc.setTextColor(30, 64, 175);

    doc.text(
        "EMPLOYEE ATTENDANCE DETAILS",
        14,
        y
    );

    doc.setDrawColor(30, 64, 175);
    doc.setLineWidth(0.5);

    doc.line(
        14,
        y + 2,
        92,
        y + 2
    );

    doc.setTextColor(0);

    y += 8;

    autoTable(doc, {
        startY: y,

        head: [
            [
                "#",
                "Emp No",
                "Employee Name",
                "Designation",
                "Section",
                "Date",
                "Status",
                "Check In",
                "Check Out",
                "Working Hours",
            ],
        ],

        body: rows.map((row, index) => [
            index + 1,
            row.empNo,
            row.employeeName,
            row.designation ?? "-",
            row.section ?? "-",
            row.date,
            row.attendanceStatus,
            row.checkIn || "N/A",
            row.checkOut || "N/A",
            row.workingHours || "--",
        ]),

        didParseCell(data) {
            if (data.section !== "body") return;

            const row = data.row.raw as (string | number | null)[];
            const status = row[6];

            if (data.column.index === 6) {
                if (status === "Present") {
                    data.cell.styles.textColor = [22, 163, 74];
                    data.cell.styles.fontStyle = "bold";
                } else if (status === "Absent") {
                    data.cell.styles.textColor = [220, 38, 38];
                    data.cell.styles.fontStyle = "bold";
                }
            }

            if ((data.column.index === 7 || data.column.index === 8) && data.cell.raw === "N/A") {
                data.cell.styles.textColor = [150, 150, 150];
                data.cell.styles.fontStyle = "italic";
            }

            if (data.column.index === 9 && data.cell.raw === "--") {
                data.cell.styles.textColor = [150, 150, 150];
            }
        },

        styles: {
            fontSize: 8,
            cellPadding: 3,
            valign: "middle",
            lineColor: [220, 220, 220],
            lineWidth: 0.1,
        },

        headStyles: {
            fillColor: [31, 41, 55],
            textColor: 255,
            fontStyle: "bold",
            fontSize: 8,
            halign: "center",
            valign: "middle",
        },

        bodyStyles: {
            textColor: 40,
        },

        alternateRowStyles: {
            fillColor: [248, 250, 252],
        },

        columnStyles: {
            0: {
                cellWidth: 15,
                halign: "center",
            },

            1: {
                cellWidth: 20,
                halign: "center",
            },

            2: {
                cellWidth: 45,
            },

            3: {
                cellWidth: 40,
            },

            4: {
                cellWidth: 28,
            },

            5: {
                cellWidth: 24,
                halign: "center",
            },

            6: {
                cellWidth: 22,
                halign: "center",
            },

            7: {
                cellWidth: 24,
                halign: "center",
            },

            8: {
                cellWidth: 24,
                halign: "center",
            },

            9: {
                cellWidth: 24,
                halign: "center",
            },
        },
    });

    if (fromDate === toDate) {
        doc.save(
            `Attendance-${fromDate}.pdf`
        );
    } else {
        doc.save(
            `Attendance-${fromDate}-${toDate}.pdf`
        );
    }


}