import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import dayjs from "dayjs";

import {
    AttendanceReport,
    AttendanceSummary,
} from "@/types/attendance";

interface ExportAttendancePdfProps {
    rows: AttendanceReport[];
    summary: AttendanceSummary;
    date: string;
    postingPlace?: string;
    section?: string;
    generatedBy?: string;
}

export function exportAttendancePdf({
    rows,
    summary,
    date,
    postingPlace = "All Posting Places",
    section = "All Sections",
    generatedBy = "System",
}: ExportAttendancePdfProps) {
    const doc = new jsPDF({
        orientation: "landscape",
        unit: "mm",
        format: "a4",
    });

    const pageWidth = doc.internal.pageSize.getWidth();

    // =============================
    // Header
    // =============================

    doc.setFillColor(30, 64, 175);
    doc.rect(0, 0, pageWidth, 28, "F");

    doc.setTextColor(255, 255, 255);

    doc.setFont("helvetica", "bold");
    doc.setFontSize(18);

    doc.text(
        "SINDH TECHNICAL EDUCATION & VOCATIONAL TRAINING AUTHORITY",
        pageWidth / 2,
        10,
        {
            align: "center",
        }
    );

    doc.setFontSize(14);

    doc.text(
        "ATTENDANCE REPORT",
        pageWidth / 2,
        19,
        {
            align: "center",
        }
    );

    doc.setTextColor(0);

    // =============================
    // Report Information
    // =============================

    let y = 38;

    doc.setFont("helvetica", "bold");
    doc.setFontSize(10);

    doc.text("Report Date", 14, y);
    doc.text("Posting Place", 14, y + 7);
    doc.text("Section", 14, y + 14);

    doc.text("Generated By", 170, y);
    doc.text("Generated On", 170, y + 7);

    doc.setFont("helvetica", "normal");

    doc.text(dayjs(date).format("DD MMM YYYY"), 45, y);

    doc.text(postingPlace, 45, y + 7);

    doc.text(section, 45, y + 14);

    doc.text(generatedBy, 205, y);

    doc.text(
        dayjs().format("DD MMM YYYY hh:mm A"),
        205,
        y + 7
    );

    y = 62;

    // divider

    doc.setDrawColor(220);
    doc.line(14, y, pageWidth - 14, y);

    y += 8;

    // =============================
    // Summary Cards
    // =============================

    interface SummaryCard {
        title: string;
        value: string | number;
        color: [number, number, number];
    }

    const cards: SummaryCard[] = [
        {
            title: "Total Staff",
            value: summary.totalStaff,
            color: [37, 99, 235],
        },
        {
            title: "Present",
            value: summary.present,
            color: [22, 163, 74],
        },
        {
            title: "Absent",
            value: summary.absent,
            color: [220, 38, 38],
        },
        {
            title: "Late",
            value: summary.late,
            color: [245, 158, 11],
        },
        {
            title: "Early Out",
            value: summary.earlyCheckout,
            color: [14, 165, 233],
        },
        {
            title: "Attendance %",
            value: `${summary.attendancePercentage}%`,
            color: [147, 51, 234],
        },
    ];

    const cardWidth = 42;
    const cardHeight = 18;
    const gap = 4;

    cards.forEach((card, index) => {
        const x = 14 + index * (cardWidth + gap);

        doc.setFillColor(...card.color);
        doc.roundedRect(
            x,
            y,
            cardWidth,
            cardHeight,
            2,
            2,
            "F"
        );

        doc.setTextColor(255);

        doc.setFontSize(9);

        doc.text(card.title, x + 3, y + 6);

        doc.setFontSize(14);

        doc.setFont("helvetica", "bold");

        doc.text(
            String(card.value),
            x + cardWidth / 2,
            y + 14,
            {
                align: "center",
            }
        );
    });

    doc.setTextColor(0);

    y += 28;

    // =============================
    // Attendance Table
    // =============================

    autoTable(doc, {
        startY: y,

        head: [
            [
                "#",
                "Emp No",
                "Employee",
                "Designation",
                "Section",
                "Status",
                "Check In",
                "Check Out",
                "Working Hours",
            ],
        ],

        body: rows.map((row, index) => [
            index + 1,
            row.empNo,
            row.employeeName,
            row.designation ?? "-",
            row.section ?? "-",
            row.attendanceStatus,
            row.checkIn ?? "-",
            row.checkOut ?? "-",
            row.workingHours ?? "-",
        ]),

        styles: {
            fontSize: 8,
            cellPadding: 2,
            valign: "middle",
        },

        headStyles: {
            fillColor: [30, 64, 175],
            textColor: 255,
            fontStyle: "bold",
            halign: "center",
        },

        bodyStyles: {
            textColor: 40,
        },

        alternateRowStyles: {
            fillColor: [245, 247, 250],
        },

        columnStyles: {
            0: { halign: "center", cellWidth: 10 },
            1: { halign: "center", cellWidth: 20 },
            5: { halign: "center", cellWidth: 22 },
            6: { halign: "center", cellWidth: 25 },
            7: { halign: "center", cellWidth: 25 },
            8: { halign: "center", cellWidth: 25 },
        },
    });

    doc.save(`Attendance-${date}.pdf`);
}